package cfgutil

var mockListJSON = []byte(`{
	"Command": "list",
	"Output": {
	  "0x908DA3869AF26": {
		"locationID": 37748736,
		"UDID": "60caa2c5dd9b45af8531290a69d5ecb1f62e0d0b",
		"ECID": "0x908DA3869AF26",
		"name": "iPhone",
		"deviceType": "iPhone8,1"
	  },
	  "0x16594A1492801E": {
		"locationID": 1048576,
		"UDID": "00008110-0016594A1492801E",
		"ECID": "0x16594A1492801E",
		"name": "iPad",
		"deviceType": "iPad14,1"
	  },
	  "0x12109C3804402E": {
		"locationID": 36700160,
		"UDID": "36850d5547880075f9c38a44fedb7ed4db385418",
		"ECID": "0x12109C3804402E",
		"name": "iPhone",
		"deviceType": "iPhone10,5"
	  }
	},
	"Type": "CommandOutput",
	"Devices": [
	  "0x16594A1492801E",
	  "0x908DA3869AF26",
	  "0x12109C3804402E"
	]
  }`)

var mockAllJSON = []byte(`{
  "Command": "get",
  "Output": {
    "Errors": {
      "0x16594A1492801E": {
        "organizationAddress": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "ICCID": {
          "Domain": "com.apple.configurator.MobileDeviceKit.amd.error",
          "FailureReason": "",
          "Message": "The value is missing.",
          "Code": -402653163
        },
        "ICCID2": {
          "Domain": "com.apple.configurator.MobileDeviceKit.amd.error",
          "FailureReason": "",
          "Message": "The value is missing.",
          "Code": -402653163
        },
        "IMEI2": {
          "Domain": "com.apple.configurator.MobileDeviceKit.amd.error",
          "FailureReason": "",
          "Message": "The value is missing.",
          "Code": -402653163
        },
        "portNumber": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "phoneNumber": {
          "Domain": "com.apple.configurator.MobileDeviceKit.amd.error",
          "FailureReason": "",
          "Message": "The value is missing.",
          "Code": -402653163
        },
        "cloudBackupsAreEnabled": {
          "Domain": "com.apple.configurator.MobileDeviceKit.amd.error",
          "FailureReason": "",
          "Message": "The value is missing.",
          "Code": -402653163
        },
        "stationNumber": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "organizationDepartment": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "organizationEmail": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "organizationPhone": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "phoneNumber2": {
          "Domain": "com.apple.configurator.MobileDeviceKit.amd.error",
          "FailureReason": "",
          "Message": "The value is missing.",
          "Code": -402653163
        },
        "organizationMagic": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "organizationName": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "IMEI": {
          "Domain": "com.apple.configurator.MobileDeviceKit.amd.error",
          "FailureReason": "",
          "Message": "The value is missing.",
          "Code": -402653163
        }
      },
      "0xA696901F0802E": {
        "ICCID2": {
          "Domain": "com.apple.configurator.MobileDeviceKit.amd.error",
          "FailureReason": "",
          "Message": "The value is missing.",
          "Code": -402653163
        },
        "portNumber": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "cloudBackupsAreEnabled": {
          "Domain": "com.apple.configurator.MobileDeviceKit.amd.error",
          "FailureReason": "",
          "Message": "The value is missing.",
          "Code": -402653163
        },
        "stationNumber": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "organizationDepartment": {
          "Domain": "ConfigurationUtilityKit.error",
          "FailureReason": "",
          "Message": "An expected value was not found.",
          "Code": 626
        },
        "phoneNumber2": {
          "Domain": "com.apple.configurator.MobileDeviceKit.amd.error",
          "FailureReason": "",
          "Message": "The value is missing.",
          "Code": -402653163
        }
      }
    },
    "0x16594A1492801E": {
      "videoDiskUsage": 0,
      "supportedPropertyNames": [
        "acceptsSupervision",
        "activationState",
        "appDiskUsage",
        "audioDiskUsage",
        "backupWillBeEncrypted",
        "batteryCurrentCapacity",
        "batteryIsCharging",
        "bluetoothAddress",
        "booksDiskUsage",
        "bootedState",
        "buildVersion",
        "cloudBackupsAreEnabled",
        "color",
        "configurationProfiles",
        "deviceClass",
        "deviceType",
        "documentsDiskUsage",
        "ECID",
        "enclosureColor",
        "ethernetAddress",
        "firmwareVersion",
        "freeDiskSpace",
        "hasTelephonyCapability",
        "humanReadableProductVersion",
        "ICCID",
        "ICCID2",
        "IMEI",
        "IMEI2",
        "installedApps",
        "isPaired",
        "isRestorable",
        "isSupervised",
        "language",
        "locale",
        "locationID",
        "logsDiskUsage",
        "name",
        "organizationAddress",
        "organizationDepartment",
        "organizationEmail",
        "organizationMagic",
        "organizationName",
        "organizationPhone",
        "otherDiskUsage",
        "pairingAllowed",
        "passcodeProtected",
        "phoneNumber",
        "phoneNumber2",
        "photosDiskUsage",
        "portNumber",
        "provisioningProfiles",
        "serialNumber",
        "stationNumber",
        "supplementalBuildVersion",
        "supportedLanguages",
        "supportedLocales",
        "supportedPropertyNames",
        "tags",
        "totalDiskCapacity",
        "totalSpaceAvailable",
        "UDID",
        "videoDiskUsage",
        "wifiAddress"
      ],
      "acceptsSupervision": true,
      "activationState": "Activated",
      "installedApps": [],
      "batteryIsCharging": false,
      "wifiAddress": "08:ff:44:8c:45:e5",
      "humanReadableProductVersion": "17.3",
      "hasTelephonyCapability": false,
      "booksDiskUsage": 0,
      "ethernetAddress": "08:ff:44:8c:a4:41",
      "serialNumber": "VKV40Y96Y6",
      "totalDiskCapacity": 64000000000,
      "ECID": "0x16594A1492801E",
      "buildVersion": "21D50",
      "appDiskUsage": 0,
      "UDID": "00008110-0016594A1492801E",
      "enclosureColor": "6",
      "locationID": 1048576,
      "provisioningProfiles": [],
      "color": "1",
      "photosDiskUsage": 5346974,
      "name": "iPad",
      "bootedState": "Booted",
      "deviceClass": "iPad",
      "locale": "en_US",
      "otherDiskUsage": 11224196356,
      "configurationProfiles": [
        {
          "identifier": "Bobs-MacBook-Pro.2B083A3D-4B47-409D-8B24-5CF4CA271EDB",
          "version": 1,
          "displayName": "homewifi_new"
        }
      ],
      "freeDiskSpace": 50790563840,
      "supportedLanguages": [
        "ko",
        "he",
        "en-AU",
        "id",
        "nl",
        "tr",
        "en-US",
        "ru",
        "pt-BR",
        "it",
        "fi",
        "hu",
        "el",
        "ar",
        "ca",
        "zh-Hant-HK",
        "sv",
        "pl",
        "da",
        "hi",
        "zh-Hant",
        "en",
        "en-IN",
        "pt-PT",
        "th",
        "nb",
        "ms",
        "cs",
        "sk",
        "zh-Hans",
        "bg",
        "kk-Cyrl",
        "es-419",
        "de",
        "vi",
        "fr-CA",
        "es",
        "ro",
        "fr",
        "uk",
        "kk",
        "zh-HK",
        "en-GB",
        "ja",
        "hr"
      ],
      "audioDiskUsage": 0,
      "totalSpaceAvailable": 63983177728,
      "tags": [],
      "isPaired": true,
      "passcodeProtected": false,
      "backupWillBeEncrypted": false,
      "supportedLocales": [
        "sv_AX",
        "en_CN",
        "ro_RO",
        "en_VG",
        "es_VC",
        "fr_MA",
        "en_AL",
        "es_TT",
        "ar_SS",
        "fr_VU",
        "fr_CI",
        "en_BW",
        "en_JM",
        "es_BS",
        "en_BD",
        "en_MG",
        "en_PT",
        "ar_LB",
        "fr_GN",
        "ru_UA",
        "en_HK",
        "en_CO",
        "en_KE",
        "en_NR",
        "fr_MU",
        "en_FI",
        "nl_BQ",
        "en_WS",
        "en_DG",
        "ar_SA",
        "en_RW",
        "en_ZM",
        "en_BE",
        "el_CY",
        "en_MH",
        "en_ER",
        "pt_AO",
        "nl_NL",
        "en_KY",
        "es_CL",
        "en_VI",
        "en_FJ",
        "es_VE",
        "fr_MC",
        "en_TZ",
        "en_ID",
        "es_TC",
        "en_GU",
        "zh_TW",
        "es_GQ",
        "en_GB",
        "es_MX",
        "es_BB",
        "es_PR",
        "fr_GP",
        "pt_GW",
        "fi_FI",
        "en_FK",
        "en_NA",
        "zh_CN",
        "en_IE",
        "en_LR",
        "en_TH",
        "ca_IT",
        "ar_KM",
        "en_BZ",
        "en_JP",
        "da_GL",
        "en_US",
        "en_BG",
        "de_CH",
        "ar_QA",
        "en_PW",
        "ar_TN",
        "fr_GQ",
        "de_LI",
        "cs_CZ",
        "hu_HU",
        "zh_HK",
        "en_NU",
        "es_VG",
        "ar_EG",
        "ro_MD",
        "en_LS",
        "fr_CM",
        "ar_SD",
        "en_GD",
        "ar_IL",
        "ar_LY",
        "en_UA",
        "fr_TD",
        "pt_LU",
        "es_PA",
        "en_KI",
        "es_CO",
        "en_FM",
        "fr_MF",
        "tr_CY",
        "ar_EH",
        "en_LT",
        "es_IC",
        "en_DK",
        "pt_ST",
        "es_GT",
        "fr_YT",
        "ms_BN",
        "en_BI",
        "he_IL",
        "pt_TL",
        "en_SS",
        "es_KY",
        "kk_KZ",
        "en_CA",
        "es_VI",
        "zh-Hant_JP",
        "fr_MG",
        "ar_MR",
        "hr_HR",
        "en_AR",
        "ar_SY",
        "fr_SN",
        "en_TK",
        "en_GY",
        "pt_CV",
        "en_MM",
        "es_ES",
        "ar_AE",
        "fr_DZ",
        "ca_ES",
        "en_001",
        "en_PG",
        "fr_RW",
        "fr_GA",
        "en_SA",
        "fr_BE",
        "hi_IN",
        "en_AS",
        "pt_MO",
        "en_LV",
        "en_DM",
        "en_LC",
        "en_GG",
        "tr_TR",
        "es_BZ",
        "it_CH",
        "zh-Hans_MO",
        "en_150",
        "it_VA",
        "fr_TG",
        "en_EE",
        "es_US",
        "en_PH",
        "es_EA",
        "es_HN",
        "en_CV",
        "sv_FI",
        "en_SB",
        "fr_RE",
        "en_CC",
        "fr_BF",
        "en_NF",
        "es_CR",
        "ms_SG",
        "en_AT",
        "ar_MA",
        "nl_BE",
        "en_GH",
        "es_GD",
        "th_TH",
        "pt_FR",
        "en_ZA",
        "en_MO",
        "es_003",
        "de_IT",
        "es_PE",
        "de_DE",
        "en_NZ",
        "en_SC",
        "en_NG",
        "en_AU",
        "el_GR",
        "en_GI",
        "ar_001",
        "en_BM",
        "ar_IQ",
        "en_MP",
        "es_PY",
        "fr_DJ",
        "es_EC",
        "en_US_POSIX",
        "vi_VN",
        "en_CX",
        "en_KN",
        "en_SD",
        "en_FR",
        "es_CA",
        "en_IL",
        "es_AR",
        "en_TO",
        "zh-Hans_HK",
        "es_GY",
        "bg_BG",
        "fr_NC",
        "en_BN",
        "en_UG",
        "en_HU",
        "uk_UA",
        "en_SX",
        "en_PK",
        "en_CY",
        "en_SE",
        "es_CU",
        "sk_SK",
        "fr_BI",
        "fr_ML",
        "de_BE",
        "en_IM",
        "fr_PF",
        "es_DM",
        "es_LC",
        "en_ZW",
        "fr_CA",
        "pl_PL",
        "pt_CH",
        "zh-Hans_JP",
        "nl_SR",
        "en_JE",
        "fr_LU",
        "ja_JP",
        "en_PL",
        "es_PH",
        "zh_MO",
        "fr_GF",
        "en_CZ",
        "fr_BJ",
        "en_IN",
        "en_AE",
        "fr_NE",
        "en_MS",
        "es_419",
        "it_IT",
        "ar_TD",
        "en_SZ",
        "fr_WF",
        "ru_MD",
        "es_SV",
        "en_SG",
        "es_CW",
        "en_CH",
        "pt_BR",
        "en_IO",
        "ar_PS",
        "en_TR",
        "ar_KW",
        "es_DO",
        "en_GM",
        "it_SM",
        "ms_MY",
        "es_UY",
        "es_BM",
        "en_MT",
        "en_PN",
        "es_HT",
        "en_KR",
        "en_SH",
        "en_VU",
        "es_KN",
        "fr_BL",
        "en_NL",
        "ca_FR",
        "en_AG",
        "fr_KM",
        "fr_SC",
        "fr_CD",
        "ko_KP",
        "nb_SJ",
        "en_BR",
        "en_MU",
        "zh-Hant_CN",
        "fr_TN",
        "ar_DZ",
        "ru_RU",
        "en_SI",
        "hr_BA",
        "en_VC",
        "ar_ER",
        "es_NI",
        "fr_HT",
        "en_TT",
        "ar_SO",
        "ca_AD",
        "fr_FR",
        "da_DK",
        "en_BS",
        "en_MV",
        "es_BO",
        "nb_NO",
        "nl_CW",
        "de_LU",
        "pt_GQ",
        "ar_JO",
        "en_CK",
        "fr_MQ",
        "zh_SG",
        "ms_ID",
        "en_AI",
        "fr_CF",
        "ko_KR",
        "en_MW",
        "en_UM",
        "en_SK",
        "en_CL",
        "en_NO",
        "fr_MR",
        "en_TV",
        "fr_SY",
        "en_TC",
        "fr_CG",
        "nl_SX",
        "es_BQ",
        "ar_YE",
        "en_MX",
        "sv_SE",
        "de_AT",
        "en_PR",
        "en_BB",
        "ar_DJ",
        "ru_BY",
        "nl_AW",
        "ar_OM",
        "en_SL",
        "en_CM",
        "ru_KZ",
        "ar_BH",
        "ru_KG",
        "id_ID",
        "pt_MZ",
        "fr_PM",
        "en_TW",
        "pt_PT",
        "es_AG",
        "en_DE",
        "en_GR",
        "fr_CH",
        "en_RU",
        "en_MY",
        "es_BR"
      ],
      "supplementalBuildVersion": "21D50",
      "batteryCurrentCapacity": 100,
      "logsDiskUsage": 20131840,
      "documentsDiskUsage": 1232805888,
      "bluetoothAddress": "08:ff:44:91:9d:3e",
      "firmwareVersion": "17.3",
      "isRestorable": true,
      "pairingAllowed": true,
      "language": "en-US",
      "deviceType": "iPad14,1",
      "isSupervised": false
    },
    "0xA696901F0802E": {
      "videoDiskUsage": 0,
      "supportedPropertyNames": [
        "acceptsSupervision",
        "activationState",
        "appDiskUsage",
        "audioDiskUsage",
        "backupWillBeEncrypted",
        "batteryCurrentCapacity",
        "batteryIsCharging",
        "bluetoothAddress",
        "booksDiskUsage",
        "bootedState",
        "buildVersion",
        "cloudBackupsAreEnabled",
        "color",
        "configurationProfiles",
        "deviceClass",
        "deviceType",
        "documentsDiskUsage",
        "ECID",
        "enclosureColor",
        "ethernetAddress",
        "firmwareVersion",
        "freeDiskSpace",
        "hasTelephonyCapability",
        "humanReadableProductVersion",
        "ICCID",
        "ICCID2",
        "IMEI",
        "IMEI2",
        "installedApps",
        "isPaired",
        "isRestorable",
        "isSupervised",
        "language",
        "locale",
        "locationID",
        "logsDiskUsage",
        "name",
        "organizationAddress",
        "organizationDepartment",
        "organizationEmail",
        "organizationMagic",
        "organizationName",
        "organizationPhone",
        "otherDiskUsage",
        "pairingAllowed",
        "passcodeProtected",
        "phoneNumber",
        "phoneNumber2",
        "photosDiskUsage",
        "portNumber",
        "provisioningProfiles",
        "serialNumber",
        "stationNumber",
        "supplementalBuildVersion",
        "supportedLanguages",
        "supportedLocales",
        "supportedPropertyNames",
        "tags",
        "totalDiskCapacity",
        "totalSpaceAvailable",
        "UDID",
        "videoDiskUsage",
        "wifiAddress"
      ],
      "acceptsSupervision": false,
      "organizationAddress": "5555 Acme Drive\nAcme Island, AK 55555",
      "activationState": "Activated",
      "installedApps": [],
      "ICCID": "89014103273306396536",
      "batteryIsCharging": false,
      "wifiAddress": "8c:86:1e:ba:aa:6c",
      "humanReadableProductVersion": "17.5.1",
      "hasTelephonyCapability": true,
      "booksDiskUsage": 0,
      "ethernetAddress": "8c:86:1e:b2:e5:80",
      "serialNumber": "C39ZC2ZGN6XW",
      "IMEI2": "353237100503375",
      "totalDiskCapacity": 256000000000,
      "ECID": "0xA696901F0802E",
      "buildVersion": "21F90",
      "appDiskUsage": 0,
      "phoneNumber": "+1 (555) 555-5555",
      "UDID": "00008030-000A696901F0802E",
      "enclosureColor": "18",
      "locationID": 17825792,
      "provisioningProfiles": [],
      "color": "1",
      "photosDiskUsage": 7299326,
      "name": "iPhone",
      "bootedState": "Booted",
      "deviceClass": "iPhone",
      "locale": "en_US",
      "organizationEmail": "mdm@acme.io",
      "otherDiskUsage": 18446744029357912988,
      "configurationProfiles": [
        {
          "identifier": "Bobs-MacBook-Pro.2B083A3D-4B47-409D-8B24-5CF4CA271EDB",
          "version": 1,
          "displayName": "homewifi_new"
        },
        {
          "identifier": "com.apple.configurator.usbrestrictedmode",
          "version": 1,
          "displayName": "USB Accessories while locked allowed"
        },
        {
          "identifier": "com.github.micromdm.micromdm.enroll",
          "version": 1,
          "displayName": "Enrollment Profile"
        }
      ],
      "freeDiskSpace": 240408899584,
      "supportedLanguages": [
        "ko",
        "he",
        "en-AU",
        "id",
        "nl",
        "tr",
        "en-US",
        "ru",
        "pt-BR",
        "it",
        "fi",
        "hu",
        "el",
        "ar",
        "ca",
        "zh-Hant-HK",
        "sv",
        "pl",
        "da",
        "hi",
        "zh-Hant",
        "en",
        "en-IN",
        "pt-PT",
        "th",
        "nb",
        "ms",
        "cs",
        "sk",
        "zh-Hans",
        "bg",
        "kk-Cyrl",
        "es-419",
        "de",
        "vi",
        "fr-CA",
        "es",
        "ro",
        "fr",
        "uk",
        "kk",
        "zh-HK",
        "en-GB",
        "ja",
        "hr"
      ],
      "organizationPhone": "555-555-5555",
      "audioDiskUsage": 0,
      "totalSpaceAvailable": 255881465856,
      "tags": [],
      "isPaired": true,
      "organizationMagic": "68885D0C-DE37-48C5-98ED-DC52ACA6898E",
      "passcodeProtected": true,
      "backupWillBeEncrypted": false,
      "organizationName": "acme",
      "supportedLocales": [
        "sv_AX",
        "en_CN",
        "ro_RO",
        "en_VG",
        "es_VC",
        "fr_MA",
        "en_AL",
        "es_TT",
        "ar_SS",
        "fr_VU",
        "fr_CI",
        "en_BW",
        "en_JM",
        "es_BS",
        "en_BD",
        "en_MG",
        "en_PT",
        "en_HK",
        "ar_LB",
        "fr_GN",
        "ru_UA",
        "en_CO",
        "en_KE",
        "en_NR",
        "fr_MU",
        "en_FI",
        "nl_BQ",
        "en_WS",
        "en_DG",
        "ar_SA",
        "en_RW",
        "en_ZM",
        "en_BE",
        "en_ER",
        "en_MH",
        "el_CY",
        "nl_NL",
        "pt_AO",
        "en_KY",
        "es_CL",
        "en_VI",
        "es_VE",
        "en_FJ",
        "fr_MC",
        "en_TZ",
        "en_ID",
        "es_TC",
        "zh_TW",
        "en_GU",
        "es_GQ",
        "en_GB",
        "ko_CN",
        "es_MX",
        "es_BB",
        "es_PR",
        "fr_GP",
        "pt_GW",
        "fi_FI",
        "en_FK",
        "en_NA",
        "zh_CN",
        "en_IE",
        "en_LR",
        "en_TH",
        "ca_IT",
        "ar_KM",
        "en_BZ",
        "de_CH",
        "en_JP",
        "en_US",
        "en_BG",
        "da_GL",
        "ar_QA",
        "en_PW",
        "ar_TN",
        "fr_GQ",
        "de_LI",
        "cs_CZ",
        "hu_HU",
        "zh_HK",
        "en_NU",
        "es_VG",
        "ar_EG",
        "ro_MD",
        "en_LS",
        "fr_CM",
        "ar_SD",
        "en_GD",
        "ar_IL",
        "ar_LY",
        "en_UA",
        "fr_TD",
        "pt_LU",
        "es_PA",
        "en_KI",
        "es_CO",
        "en_FM",
        "fr_MF",
        "tr_CY",
        "ar_EH",
        "en_LT",
        "es_IC",
        "en_DK",
        "pt_ST",
        "es_GT",
        "fr_YT",
        "ms_BN",
        "en_BI",
        "he_IL",
        "pt_TL",
        "en_SS",
        "es_KY",
        "kk_KZ",
        "en_CA",
        "es_VI",
        "ar_MR",
        "fr_MG",
        "zh-Hant_JP",
        "en_AR",
        "hr_HR",
        "ar_SY",
        "fr_SN",
        "en_TK",
        "en_GY",
        "pt_CV",
        "en_MM",
        "es_ES",
        "ar_AE",
        "fr_DZ",
        "en_001",
        "en_PG",
        "ca_ES",
        "fr_RW",
        "fr_GA",
        "en_SA",
        "fr_BE",
        "hi_IN",
        "en_AS",
        "pt_MO",
        "en_LV",
        "en_DM",
        "en_LC",
        "en_GG",
        "tr_TR",
        "es_BZ",
        "it_CH",
        "zh-Hans_MO",
        "en_150",
        "it_VA",
        "fr_TG",
        "es_US",
        "en_EE",
        "es_EA",
        "es_HN",
        "sv_FI",
        "en_CV",
        "ms_SG",
        "en_SB",
        "fr_RE",
        "en_CC",
        "fr_BF",
        "en_NF",
        "es_CR",
        "en_PH",
        "en_AT",
        "ar_MA",
        "nl_BE",
        "en_GH",
        "th_TH",
        "en_ZA",
        "pt_FR",
        "es_GD",
        "en_MO",
        "es_003",
        "de_IT",
        "es_PE",
        "de_DE",
        "en_SC",
        "en_NZ",
        "en_NG",
        "en_AU",
        "el_GR",
        "en_GI",
        "ar_001",
        "en_BM",
        "ar_IQ",
        "en_MP",
        "es_PY",
        "fr_DJ",
        "es_EC",
        "vi_VN",
        "en_US_POSIX",
        "en_CX",
        "en_KN",
        "en_SD",
        "en_FR",
        "es_CA",
        "en_IL",
        "es_AR",
        "en_TO",
        "zh-Hans_HK",
        "es_GY",
        "bg_BG",
        "fr_NC",
        "en_BN",
        "en_UG",
        "en_HU",
        "en_PK",
        "uk_UA",
        "en_SX",
        "en_CY",
        "en_SE",
        "es_CU",
        "sk_SK",
        "fr_BI",
        "fr_ML",
        "de_BE",
        "en_IM",
        "fr_PF",
        "es_DM",
        "es_LC",
        "en_ZW",
        "fr_CA",
        "pl_PL",
        "pt_CH",
        "nl_SR",
        "en_JE",
        "zh-Hans_JP",
        "fr_LU",
        "ja_JP",
        "en_PL",
        "zh_MO",
        "en_CZ",
        "fr_GF",
        "es_PH",
        "fr_BJ",
        "en_IN",
        "en_AE",
        "fr_NE",
        "en_MS",
        "es_419",
        "it_IT",
        "ar_TD",
        "en_SZ",
        "fr_WF",
        "ru_MD",
        "es_SV",
        "en_SG",
        "es_CW",
        "en_CH",
        "pt_BR",
        "en_IO",
        "ar_PS",
        "en_TR",
        "ar_KW",
        "es_DO",
        "en_GM",
        "it_SM",
        "ms_MY",
        "es_UY",
        "en_MT",
        "es_BM",
        "en_PN",
        "es_HT",
        "en_KR",
        "en_SH",
        "es_KN",
        "en_VU",
        "fr_BL",
        "en_NL",
        "ca_FR",
        "en_AG",
        "fr_KM",
        "fr_SC",
        "fr_CD",
        "ko_KP",
        "nb_SJ",
        "zh-Hant_CN",
        "en_BR",
        "ru_RU",
        "fr_TN",
        "ar_DZ",
        "en_MU",
        "en_SI",
        "hr_BA",
        "es_NI",
        "en_VC",
        "ar_ER",
        "fr_HT",
        "en_TT",
        "ar_SO",
        "ca_AD",
        "fr_FR",
        "da_DK",
        "en_BS",
        "nl_CW",
        "es_BO",
        "nb_NO",
        "en_MV",
        "de_LU",
        "pt_GQ",
        "en_CK",
        "ar_JO",
        "fr_MQ",
        "zh_SG",
        "ms_ID",
        "en_AI",
        "fr_CF",
        "ko_KR",
        "en_MW",
        "en_UM",
        "en_SK",
        "en_CL",
        "en_NO",
        "fr_MR",
        "en_TV",
        "fr_SY",
        "en_TC",
        "fr_CG",
        "nl_SX",
        "es_BQ",
        "ar_YE",
        "ru_BY",
        "sv_SE",
        "en_BB",
        "de_AT",
        "en_PR",
        "ar_DJ",
        "en_MX",
        "nl_AW",
        "ar_OM",
        "en_SL",
        "en_CM",
        "ru_KZ",
        "ar_BH",
        "ru_KG",
        "pt_MZ",
        "id_ID",
        "fr_PM",
        "en_TW",
        "es_AG",
        "pt_PT",
        "en_DE",
        "fr_CH",
        "en_GR",
        "en_RU",
        "en_MY",
        "es_BR"
      ],
      "supplementalBuildVersion": "21F90",
      "batteryCurrentCapacity": 100,
      "logsDiskUsage": 20738048,
      "documentsDiskUsage": 2077069312,
      "bluetoothAddress": "8c:86:1e:ac:2f:6a",
      "firmwareVersion": "17.5.1",
      "IMEI": "353237100347021",
      "isRestorable": true,
      "pairingAllowed": true,
      "language": "en-US",
      "deviceType": "iPhone12,3",
      "isSupervised": true
    }
  },
  "Type": "CommandOutput",
  "Devices": [
    "0x16594A1492801E",
    "0xA696901F0802E"
  ]
}`)
